Add custom kernel support. Print pkg(8) branch option. Change pkg(8) packages install way. Make sure to clean up after work or fail. Improve help message.

diff --git a/verimg b/verimg
--- a/verimg
+++ b/verimg
@@ -26,7 +26,7 @@
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 # ------------------------------
-# UNATTENDED VM IMAGE BUILDER
+# UNATTENDED VM(s) IMAGE BUILDER
 # ------------------------------
 # vermaden [AT] interia [DOT] pl
 # https://vermaden.wordpress.com
@@ -38,10 +38,12 @@ ARG_SIZE=${ARG_SIZE:-"10g"}
 ARG_VERS=${ARG_VERS:-"releng/15.0"}
 ARG_INST=${ARG_INST:-"beadm:lsblk"}
 ARG_MNTD=${ARG_MNTD:-"/mnt"}
+ARG_KERN=${ARG_KERN:-"GENERIC"}
 ARG_SRCD=${ARG_SRCD:-"/usr/src"}
 ARG_TYPE=${ARG_TYPE:-"img"}
 ARG_REPO=${ARG_REPO:-"/usr/obj/usr/src/repo/FreeBSD:15:$( uname -m )/latest"}
 ARG_POOL=${ARG_POOL:-"sys"}
+ARG_BRCH=${ARG_BRCH:-"latest"}
 ARG_BRCH=${ARG_BRCH:-"latest"}
 
 # pkg(8) KEYS
@@ -55,46 +57,30 @@ AWS_KEY="1d7b45d20fa8d6ed26f9b4a13ac81a6b5df860b9fe644d07b87e92298ba72595"
 # TRAP FUNCTION TO CLEANUP (begin)
 __verimg_clean() {
 
+  # UNMOUNT devfs(5) FILESYSTEM FROM CHROOT
+  umount -f "${ARG_MNTD}/dev" 2> /dev/null
+
   # EXPORT CREATE ZFS POOL
   if zpool list ${ARG_POOL} 1> /dev/null 2> /dev/null
   then
-
-    if ! zpool export -f ${ARG_POOL} 2> /dev/null
-    then
-      echo "NOPE: can not export ZFS '${ARG_POOL}' pool"
-    else
-      echo "INFO: ZFS '${ARG_POOL}' pool exported"
-    fi
-
+    zpool export -f ${ARG_POOL} 2> /dev/null
   fi
 
   # UNMAPE FILE FROM md(4) NODE
   if [ "${DEVICE}" != "" ]
   then
-
-    if ! mdconfig -d -u /dev/${DEVICE} 2> /dev/null
-    then
-      echo "NOPE: can not unmap md(4) '/dev/${DEVICE}' device"
-    else
-      echo "INFO: md(4) device unmapped from '/dev/${DEVICE}' node"
-    fi
-
+    mdconfig -d -u /dev/${DEVICE} 2> /dev/null
   fi
 
   # CHECK IF DISK IMAGE IS ALREADY MAPPED WITH md(4) DRIVER ON OTHER PLACES
   ARG_FILE_PATH="$( pwd )/${ARG_FILE}"
-  mdconfig -l -v \
+  mdconfig -l -v 2> /dev/null \
     | while read NAME TYPE SIZE FILENAME GARBAGE
       do
 
         if [ "${ARG_FILE_PATH}" = "${FILENAME}" ]
         then
-
-          if ! mdconfig -d -u /dev/${NAME}
-          then
-            echo "NOPE: can not unmap '${ARG_FILE}' from '/dev/${NAME}' place"
-          fi
-
+          mdconfig -d -u /dev/${NAME} 2> /dev/null
         fi
 
       done
@@ -120,6 +106,8 @@ __usage() {
   echo "  -p POOL  specify ZFS pool name (default: sys)"
   echo "  -b BRCH  specify branch for pkg(8) (default: latest)"
   echo "  -n       display options and exit"
+  echo "  -k LIST  list of kernel configs to build in CONF1:CONF2:CONF3 format"
+  echo "           if unspecified then only the GENERIC kernel will be built"
   echo "  -t TYPE  type of operation is one of options:"
   echo "           = img"
   echo "             - create FILE backend and do setup there (default)"
@@ -139,7 +127,30 @@ __usage() {
   echo "             - setup FreeBSD from /usr/obj PKGBASE repository"
   echo
   echo "examples:"
-  echo "  # verimg.sh -f FILE -s 20g -r releng/15.0 -i python:ansible"
+  echo "  # verimg.sh -n -M setup -s 20g -r releng/15.0 -i lsblk:beadm:python:ansible"
+  echo "  INFO: options that will be used                          "
+  echo "    ARG_MODE: setup                                        "
+  echo "    ARG_TYPE: img                                          "
+  echo "    ARG_FILE: VERIMG                                       "
+  echo "    ARG_SIZE: 20g                                          "
+  echo "    ARG_VERS: releng/15.0                                  "
+  echo "    ARG_INST: beadm:lsblk:python:ansible                   "
+  echo "    ARG_MNTD: /mnt                                         "
+  echo "    ARG_SRCD: /usr/src                                     "
+  echo "    ARG_KERN: GENERIC                                      "
+  echo "    ARG_POOL: sys                                          "
+  echo "    ARG_REPO: /usr/obj/usr/src/repo/FreeBSD:15:amd64/latest"
+  echo
+  echo "cleanup:"
+  echo "  ${NAME}(8) takes care to clean up (unmount/export/...) after job is done/fail"
+  echo "  but if for some reason it does not clean up properly - use this manual way"
+  echo "    # umount -f ${ARG_MNTD}/dev"
+  echo "    # zpool export -f ${ARG_POOL}"
+  echo "    # mdconfig -d -u /dev/md0"
+  echo
+  echo "  md(4) device may be other then /dev/md0 so check with mdconfig(8) command"
+  echo "    # mdconfig -l -v"
+  echo "    md0     vnode      10G  /home/vermaden/VERIMG   -"
   echo
   exit 1
   }
@@ -160,6 +171,7 @@ __verimg_fetch() {
   if ! which git 1> /dev/null 2> /dev/null
   then
     echo "NOPE: install 'devel/git' package"
+    __verimg_clean
     exit 1
   fi
 
@@ -168,6 +180,7 @@ __verimg_fetch() {
   if ! git clone -b "${ARG_VERS}" --depth 1 https://git.freebsd.org/src.git ${ARG_SRCD} 2> /dev/null
   then
     echo "NOPE: can not fetch FreeBSD '${ARG_VERS}' source into '${ARG_SRCD}' dir"
+    __verimg_clean
     exit 1
   fi
 
@@ -181,14 +194,29 @@ __verimg_build() {
   if ! cd ${ARG_SRCD} 2> /dev/null
   then
     echo "NOPE: can not cd(1) into '${ARG_SRCD}' dir."
+    __verimg_clean
     exit 1
   fi
 
+  # CHECK ALL '${ARG_KERN}' KERNEL CONFIG FILES EXIST
+  KERNCONF=$( echo ${ARG_KERN} | tr ':' ' ' )
+  ARCH=$( uname -m )
+  for CONFIG in ${KERNCONF}
+  do
+    if [ ! -f ${ARG_SRCD}/sys/${ARCH}/conf/${CONFIG}
+    then
+      echo "NOPE: kernel config file '${CONFIG}' does not exists"
+      __verimg_clean
+      exit 1
+    fi
+  done
+
   # BUILD FREEBSD USERSPACE/KERNEL AND PKGBASE PACKAGES
-  __m "make -j $( nproc --ignore=1 ) buildworld buildkernel update-packages"
-  if ! make -j $( nproc --ignore=1 ) buildworld buildkernel update-packages 2> /dev/null
+  __m "make -j $( nproc --ignore=1 ) buildworld buildkernel KERNCONF='${KERNCONF}' update-packages KERNCONF='${KERNCONF}'"
+  if ! make -j $( nproc --ignore=1 ) buildworld buildkernel KERNCONF="${KERNCONF}" update-packages KERNCONF="${KERNCONF}" 2> /dev/null
   then
     echo "NOPE: can not build FreeBSD from '${ARG_SRCD}' source"
+    __verimg_clean
     exit 1
   fi
 
@@ -203,6 +231,7 @@ __verimg_setup() {
   if ! cd "${ARG_REPO}" 2> /dev/null
   then
     echo "NOPE: can not cd(1) into '${ARG_REPO}' dir"
+    __verimg_clean
     exit 1
   fi
 
@@ -211,6 +240,7 @@ __verimg_setup() {
   if ! pkg repo . 2> /dev/null
   then
     echo "NOPE: can not create pkg-repo(8) in '${ARG_REPO}' dir"
+    __verimg_clean
     exit 1
   fi
 
@@ -219,6 +249,7 @@ __verimg_setup() {
   if ! mkdir -p /usr/obj/repos 2> /dev/null
   then
     echo "NOPE: can not create '/usr/obj/repos' dir"
+    __verimg_clean
     exit 1
   fi
 
@@ -232,6 +263,7 @@ FreeBSD-base: {
 EOF
   then
     echo "NOPE: can not create /usr/obj/repos/FreeBSD-base.conf config"
+    __verimg_clean
     exit 1
   fi
 
@@ -244,6 +276,7 @@ EOF
          "${ARG_MNTD}/usr/share/keys/pkgbase-15/revoked" 2> /dev/null
   then
     echo "NOPE: can not create pkg(8) keys dirs"
+    __verimg_clean
     exit 1
   fi
 
@@ -272,6 +305,7 @@ EOF
   if [ ${?} -ne 0 ]
   then
     echo "NOPE: can not create pkg(8) keys"
+    __verimg_clean
     exit 1
   fi
 
@@ -280,6 +314,7 @@ EOF
   if ! mkdir -p "${ARG_MNTD}/etc" "${ARG_MNTD}/boot" 2> /dev/null
   then
     echo "NOPE: can not create /boot OR /etc DIRS"
+    __verimg_clean
     exit 1
   fi
 
@@ -313,6 +348,7 @@ EOF
   if [ ${?} -ne 0 ]
   then
     echo "NOPE: can not populate configs"
+    __verimg_clean
     exit 1
   fi
 
@@ -322,15 +358,40 @@ EOF
          update 2> /dev/null
   then
     echo "NOPE: can not update pkg(8) repos"
+    __verimg_clean
     exit 1
   fi
 
+  # MOUNT devfs(5) FILESYSTEM INSIDE CHROOT BECAUSE pkg(8) NEEDS /dev/null TO WORK
+  mkdir -p                  "${ARG_MNTD}/dev"
+  __m "mount -t devfs devfs '${ARG_MNTD}/dev'"
+  if ! mount -t devfs devfs "${ARG_MNTD}/dev" 2> /dev/null
+  then
+    echo "NOPE: can not mount devfs(5) inside '${ARG_MNTD}' dir"
+    __verimg_clean
+    exit 1
+  fi
+
+  echo "# mount -p | grep -v zfs | column -t"
+          mount -p | grep -v zfs | column -t
+
+  # PREPARE POTENTIAL CUSTOM KERNEL(s) LIST FOR pkg(8) TO INSTALL
+  if [ "${ARG_KERN}" != "GENERIC" ]
+  then
+    CUSTOM_KERNELS_LIST=$( echo "${ARG_KERN}" | tr ':' ' ' | tr 'A-Z' 'a-z' )
+    for I in ${CUSTOM_KERNELS_LIST}
+    do
+      CUSTOM_KERNELS="${CUSTOM_KERNELS} FreeBSD-kernel-${I} FreeBSD-kernel-${I}-dbg"
+    done
+  fi
+
   # INSTALL PKGBASE FreeBSD-set-base SET
-  __m "pkg --rootdir ${ARG_MNTD} --repo-conf-dir /usr/obj/repos -o IGNORE_OSVERSION=yes install -r FreeBSD-base -U -y FreeBSD-set-base"
+  __m "pkg --rootdir ${ARG_MNTD} --repo-conf-dir /usr/obj/repos -o IGNORE_OSVERSION=yes install -r FreeBSD-base -U -y FreeBSD-set-base ${CUSTOM_KERNELS}"
   if ! pkg --rootdir "${ARG_MNTD}" --repo-conf-dir /usr/obj/repos -o IGNORE_OSVERSION=yes \
-         install -r FreeBSD-base -U -y FreeBSD-set-base 2> /dev/null
+         install -r FreeBSD-base -U -y FreeBSD-set-base ${CUSTOM_KERNELS} 2> /dev/null
   then
     echo "NOPE: can not install 'FreeBSD-set-base' set"
+    __verimg_clean
     exit 1
   fi
 
@@ -339,6 +400,7 @@ EOF
   if ! mkdir -p "${ARG_MNTD}/usr/local/etc/pkg/repos" 2> /dev/null
   then
     echo "NOPE: can not create '${ARG_MNTD}/usr/local/etc/pkg/repos' dir"
+    __verimg_clean
     exit 1
   fi
 
@@ -351,6 +413,7 @@ EOF
            > "${ARG_MNTD}/usr/local/etc/pkg/repos/FreeBSD.conf" 2> /dev/null
     then
       echo "NOPE: can not set '${ARG_BRCH}' pkg(8) branch"
+      __verimg_clean
       exit 1
     fi
   fi
@@ -360,22 +423,34 @@ EOF
   if ! echo 'FreeBSD-base: { enabled: yes }' >> "${ARG_MNTD}/usr/local/etc/pkg/repos/FreeBSD.conf" 2> /dev/null
   then
     echo "NOPE: can not enable PKGBASE in pkg(8) '${ARG_MNTD}/usr/local/etc/pkg/repos/FreeBSD.conf' config"
+    __verimg_clean
     exit 1
   fi
 
   # UPDATE AND BOOTSTRAP pkg(1) IN CHROOT
-  __m "pkg --chroot ${ARG_MNTD} update"
-  if ! pkg --chroot "${ARG_MNTD}" update 2> /dev/null
+  __m "chroot '${ARG_MNTD}' env ASSUME_ALWAYS_YES=yes pkg update"
+  if ! chroot "${ARG_MNTD}" env ASSUME_ALWAYS_YES=yes pkg update 2> /dev/null
   then
     echo "NOPE: can not update pkg(8) in chroot dir"
+    __verimg_clean
     exit 1
   fi
 
   # INSTALL REQUIRED pkg(8) PACKAGES
-  __m "pkg --chroot ${ARG_MNTD} install -y $( echo ${ARG_INST} | tr ':' ' ' )"
-  if ! pkg --chroot "${ARG_MNTD}" install -y $( echo "${ARG_INST}" | tr ':' ' ' ) 2> /dev/null
+  __m "chroot '${ARG_MNTD}' env ASSUME_ALWAYS_YES=yes pkg install -y $( echo ${ARG_INST} | tr ':' ' ' )"
+  if ! chroot "${ARG_MNTD}" env ASSUME_ALWAYS_YES=yes pkg install -y $( echo ${ARG_INST} | tr ':' ' ' ) 2> /dev/null
   then
     echo "NOPE: can not install specified pkg(8) packages"
+    __verimg_clean
+    exit 1
+  fi
+
+  # UNMOUNT devfs(5) FILESYSTEM FROM CHROOT
+  __m "umount -f '${ARG_MNTD}/dev'"
+  if ! umount -f "${ARG_MNTD}/dev" 2> /dev/null
+  then
+    echo "NOPE: can not unmount devfs(5) from '${ARG_MNTD}' dir"
+    __verimg_clean
     exit 1
   fi
 
@@ -386,6 +461,7 @@ EOF
     if ! zpool set bootfs="${ARG_POOL}/ROOT/default" "${ARG_POOL}" 2> /dev/null
     then
       echo "NOPE: can not setup 'bootfs' ZFS pool property"
+      __verimg_clean
       exit 1
     fi
 
@@ -394,6 +470,7 @@ EOF
     if ! zpool export "${ARG_POOL}" 2> /dev/null
     then
       echo "NOPE: can not export '${ARG_POOL}' ZFS pool"
+      __verimg_clean
       exit 1
     fi
 
@@ -406,6 +483,7 @@ EOF
       if ! mdconfig -d -u "/dev/${DEVICE}" 2> /dev/null
       then
         echo "NOPE: can not unmap md(4) device"
+        __verimg_clean
         exit 1
       fi
 
@@ -478,6 +556,7 @@ __verimg_image() {
   if ! truncate -s "${ARG_SIZE}" "${ARG_FILE}" 2> /dev/null
   then
     echo "NOPE: truncate(1) is not able to create '${ARG_FILE}' file."
+    __verimg_clean
     exit 1
   fi
 
@@ -487,6 +566,7 @@ __verimg_image() {
   if ! echo "${DEVICE}" | grep -q -E '^md[0-9]+$' 2> /dev/null
   then
     echo "NOPE: can not map '${ARG_FILE}' file with md(4) driver."
+    __verimg_clean
     exit 1
   fi
 
@@ -503,6 +583,7 @@ __verimg_image() {
   if [ ${?} -ne 0 ]
   then
     echo "NOPE: can not create gpart(8) partitions"
+    __verimg_clean
     exit 1
   fi
 
@@ -511,6 +592,7 @@ __verimg_image() {
   if ! newfs_msdos -F 32 -c 1 "/dev/${DEVICE}p2" 2> /dev/null
   then
     echo "NOPE: can not create FAT32 filesystem for UEFI partition"
+    __verimg_clean
     exit 1
   fi
 
@@ -519,6 +601,7 @@ __verimg_image() {
   if ! mkdir -p "${ARG_MNTD}/efi" 2> /dev/null
   then
     echo "NOPE: can not create UEFI dir."
+    __verimg_clean
     exit 1
   fi
 
@@ -527,6 +610,7 @@ __verimg_image() {
   if ! mount_msdosfs "/dev/${DEVICE}p2" "${ARG_MNTD}/efi" 2> /dev/null
   then
     echo "NOPE: can not mount UEFI partition"
+    __verimg_clean
     exit 1
   fi
 
@@ -535,6 +619,7 @@ __verimg_image() {
   if ! mkdir -p "${ARG_MNTD}/efi/EFI/BOOT" 2> /dev/null
   then
     echo "NOPE: can not create UEFI dirs"
+    __verimg_clean
     exit 1
   fi
 
@@ -543,6 +628,7 @@ __verimg_image() {
   if ! cp /boot/loader.efi "${ARG_MNTD}/efi/EFI/BOOT/bootx64.efi" 2> /dev/null
   then
     echo "NOPE: can not install 'loader.efi' into UEFI partition"
+    __verimg_clean
     exit 1
   fi
 
@@ -559,6 +645,7 @@ __verimg_image() {
     if ! zpool create -R "${ARG_MNTD}" -O compress=lz4 -O atime=off -m none -f ${ARG_POOL} "${DEVICE}p4" 2> /dev/null
     then
       echo "NOPE: can not create ZFS 'sys' pool"
+      __verimg_clean
       exit 1
     fi
 
@@ -582,6 +669,7 @@ __verimg_image() {
     if [ ${?} -ne 0 ]
     then
       echo "NOPE: can not create ZFS datasets"
+      __verimg_clean
       exit 1
     fi
 
@@ -603,8 +691,10 @@ __verimg_print() {
   echo "  ARG_INST: ${ARG_INST}"
   echo "  ARG_MNTD: ${ARG_MNTD}"
   echo "  ARG_SRCD: ${ARG_SRCD}"
+  echo "  ARG_KERN: ${ARG_KERN}"
   echo "  ARG_POOL: ${ARG_POOL}"
   echo "  ARG_REPO: ${ARG_REPO}"
+  echo "  ARG_BRCH: ${ARG_BRCH}"
   echo
 
   }
@@ -614,7 +704,7 @@ __verimg_print() {
 case "${1}" in
   (--version|-version|version)
     echo
-    echo " verbsd(8) 0.2 2026/04/19"
+    echo "verimg 0.3 2026/04/24"
     echo
     exit 0
     ;;
@@ -628,23 +718,24 @@ case "${1}" in
 esac
 
 # OBTAIN ARGUMENTS FOR OPTIONS
-while getopts M:t:f:s:S:r:i:m:R:p:b:n ARG
+while getopts M:t:f:s:S:r:i:m:R:p:k:b:n ARG
 do
   case "${ARG}" in
-    (M) ARG_MODE="${OPTARG}" ;;
-    (t) ARG_TYPE="${OPTARG}" ;;
-    (f) ARG_FILE="${OPTARG}" ;;
-    (s) ARG_SIZE="${OPTARG}" ;;
-    (r) ARG_VERS="${OPTARG}" ;;
-    (i) ARG_INST="${OPTARG}" ;;
-    (m) ARG_MNTD="${OPTARG}" ;;
+    (M) ARG_MODE="${OPTARG}"                                                 ;;
+    (t) ARG_TYPE="${OPTARG}"                                                 ;;
+    (f) ARG_FILE="${OPTARG}"                                                 ;;
+    (s) ARG_SIZE="${OPTARG}"                                                 ;;
+    (r) ARG_VERS="${OPTARG}"                                                 ;;
+    (i) ARG_INST="${OPTARG}"                                                 ;;
+    (m) ARG_MNTD="${OPTARG}"                                                 ;;
     (S) ARG_SRCD="${OPTARG}"
         ARG_REPO="/usr/obj/${ARG_SRCD}/repo/FreeBSD:15:$( uname -m )/latest" ;;
-    (R) ARG_REPO="${OPTARG}" ;;
-    (s) ARG_POOL="${OPTARG}" ;;
-    (b) ARG_BRCH="${OPTARG}" ;;
-    (n) ARG_NDRY="yes"       ;;
-    (*) __usage              ;;
+    (R) ARG_REPO="${OPTARG}"                                                 ;;
+    (k) ARG_KERN="GENERIC:${OPTARG}"                                         ;;
+    (s) ARG_POOL="${OPTARG}"                                                 ;;
+    (b) ARG_BRCH="${OPTARG}"                                                 ;;
+    (n) ARG_NDRY="yes"                                                       ;;
+    (*) __usage                                                              ;;
   esac
 done
 
